AWSTemplateFormatVersion: '2010-09-09'
Description: Creating Infrastucture

Resources:

  # creation roles for lambda

  LambdaChannelSenderRole1:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MlamdaSqsRole
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Path: /